### PR TITLE
#32 Granite Code on Continue in VSCode

### PR DESCRIPTION
**Pull request by fayvor**
Provide instructions and examples for:
- Installing Granite Code models using Ollama
- Setting up Continue in VSCode
- Using Granite Code models for chat in Continue

Not in this PR:
- Using Granite Code models for tab Auto-Complete

### CODE REVIEW

**Comment by fayvor** [comment]
This is a draft PR for cursory review to make sure I'm on the right track. Also to discuss some conventions:

- Should we use Markdown or something else for this type of recipe? There is no executable code, so no Jupyter Notebook.
- Is it possible to link PRs back to issues in the "pm" repo?

**Comment by fayvor** [comment]
Putting this up as Ready for Review. I've moved it to a Jupyter notebook and added a section for testing code generation from within the notebook.

Let me know if I should squash the commits.

**Comment by deanwampler** [comment]
_Is it possible to link PRs back to issues in the "pm" repo?_

I guess the only option is a full URL, e.g., 
[pm/#32](https://github.com/ibm-granite-cookbooks/pm/issues/32)?

**Comment by deanwampler** [comment]
Looks good. Let's merge this, then some follow ups:
1. First, I think you should just create work branches in the main repo. They are far easier to work with, IMHO. 
2. Once merged, I'll do a PR for a few minor suggestions.
3. I don't think we want all the recipes living in one folder, as this will break down quickly. I suggest:
    * Create a folder per recipe.
    * Consider a naming convention to highlight the first recipes users should try, like `00 - Getting_Started_with_Granite_Code.ipynb` (for Adam's notebook that isn't on `main` yet). The disadvantage is you only need this for the first few recipes, then they can be used (or not) in any order. Thoughts? 
    * Should images go in one universal folder, like `recipes/images`, which enables sharing? Alternatively, keeping them in the same directory as the recipe by default, and then using `recipes/images` for shared images might be easier. For example, we'll want to consider adding the granite image to all notebooks and markdown files.

**Review by deanwampler — APPROVED** [review]
👍

**Comment by deanwampler** [comment]
The DCO stuff is such a pain. It looks Adam has a commit in the log that isn't signed. @fayvor perhaps if you squash the commits, this will fix it? I don't know if that actually erases the problem.

**Comment by deanwampler** [comment]
**Pro Tip:** I found out the hard way the other day that editing files directly in the GitHub page and committing does not sign the commits. I haven't found a way to configure this and the commit dialog doesn't provide the option.

**Comment by fayvor** [comment]
@deanwampler  
> 1. First, I think you should just create work branches in the main repo. They are far easier to work with, IMHO.
I was following the [contribution guidelines](https://github.com/ibm-granite-cookbooks/community/blob/main/CONTRIBUTING.md#creating-a-contribution), but I would be happy to just create branches on this repo, if I can get the permissions.

> 2. Once merged, I'll do a PR for a few minor suggestions.
> 3. I don't think we want all the recipes living in one folder, as this will break down quickly. I suggest:
>    
>    * Create a folder per recipe.
Makes sense.

>    * Consider a naming convention to highlight the first recipes users should try, like `00 - Getting Started with Granite Code` (for Adam's notebook that isn't on `main` yet). The disadvantage is you only need this for the first few recipes, then they can be used (or not) in any order. Thoughts?
That would work for highlighting the first recipes, but might get hard to maintain order on the rest of them. Maybe we set up a separate site map or table of contents?

>    * Should images go in one universal folder, like `recipes/images`, which enables sharing? Alternatively, keeping them in the same directory as the recipe by default, and then using `recipes/images` for shared images might be easier. For example, we'll want to consider adding the granite image to all notebooks and markdown files.
I like the idea of keeping them with the recipe by default, and using `recipes/images` for shared images.

**Comment by deanwampler** [comment]
> @deanwampler
> 
> > 1. First, I think you should just create work branches in the main repo. They are far easier to work with, IMHO.
> 
> I was following the [contribution guidelines](https://github.com/ibm-granite-cookbooks/community/blob/main/CONTRIBUTING.md#creating-a-contribution), but I would be happy to just create branches on this repo, if I can get the permissions.

The rules don't apply to us elites! 😁 . I should amend the description for committers like us. If you don't have the necessary permission, we should give it to you.

> > 2. Once merged, I'll do a PR for a few minor suggestions.

Go ahead and merge this once you sort out the problem with the unsigned commit.

> > 3. I don't think we want all the recipes living in one folder, as this will break down quickly. I suggest:
> >    
> >    * Create a folder per recipe.
> 
> Makes sense.

👍 
 
> > * Consider a naming convention to highlight the first recipes users should try, like `00 - Getting Started with Granite Code` (for Adam's notebook that isn't on `main` yet). The disadvantage is you only need this for the first few recipes, then they can be used (or not) in any order. Thoughts?
> 
> That would work for highlighting the first recipes, but might get hard to maintain order on the rest of them. Maybe we set up a separate site map or table of contents?
> 

That's a good idea! Yes, let's do that.

> > * Should images go in one universal folder, like `recipes/images`, which enables sharing? Alternatively, keeping them in the same directory as the recipe by default, and then using `recipes/images` for shared images might be easier. For example, we'll want to consider adding the granite image to all notebooks and markdown files.
> 
> I like the idea of keeping them with the recipe by default, and using `recipes/images` for shared images.

👍

**Comment by fayvor** [comment]
> The DCO stuff is such a pain. It looks like Adam has a commit ([9da443f](https://github.com/ibm-granite-cookbooks/granite-code-cookbook/commit/9da443fc6952605855f26f0d5f375daa68786d5a)) in the log that isn't signed. @fayvor perhaps if you squash the commits, this will fix it? I don't know if that actually erases the problem.

@deanwampler I've squashed my commits, in case that helps. Adam says that Github isn't signing PR merge commits, which sounds like it will require some configuration; he's looking into it.

**Pull request merged**
